services:
  web:
    image: ${WEB_IMAGE}
    expose:
      - "8000"
    depends_on:
      - db
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "8000:443"
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./web/certs:/etc/nginx/certs:ro
    depends_on:
      - web
    restart: unless-stopped

  db:
    image: ${DB_IMAGE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata: